### ISSUE TITLE
Re-used localimport object adds local modules back to sys.modules but removes them again immediately

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/localimport#15]
``` python
imp = _localimport('numpy-1.10.4-py2.7-win-amd64-vs090')
with imp:
    import numpy
    arr = numpy.array([1, 2, 3])
    print(arr)
assert 'numpy' not in sys.modules
with imp:
    print('>>', sys.modules['numpy.core'])
    arr = numpy.array([1, 2, 3])
    print(arr)
assert 'numpy' not in sys.modules
```

Added prints to `_localimport.__enter__()`:

```
[1 2 3]
('Putting back', 'numpy.random.warnings')
('Putting back', 'numpy.linalg.linalg')
('Putting back', 'numpy.lib._iotools')
('Putting back', 'numpy.random.operator')
('Putting back', 'numpy.core.info')
('Putting back', 'numpy.core.shape_base')
('Putting back', 'numpy.core')
('Putting back', 'numpy.linalg')
('Putting back', 'numpy.random')
('Putting back', 'numpy.lib.shape_base')
('Putting back', 'numpy.lib.polynomial')
('Putting back', 'numpy.compat')
('Putting back', 'numpy._import_tools')
('Putting back', 'numpy.lib.twodim_base')
('Putting back', 'numpy.core.numeric')
('Putting back', 'numpy.polynomial')
('Putting back', 'numpy.fft.info')
('Putting back', 'numpy.core.records')
('Putting back', 'numpy.core.numerictypes')
('Putting back', 'numpy.polynomial.legendre')
('Putting back', 'numpy.random.mtrand')
('Putting back', 'numpy.__config__')
('Putting back', 'numpy.matrixlib')
('Putting back', 'numpy.random.numpy')
('Putting back', 'numpy.lib.financial')
('Putting back', 'numpy.random.info')
('Putting back', 'numpy.testing.decorators')
('Putting back', 'numpy.linalg.info')
('Putting back', 'numpy.lib.npyio')
('Putting back', 'numpy.testing')
('Putting back', 'numpy.lib.numpy')
('Putting back', 'numpy.core.arrayprint')
('Putting back', 'numpy.random.threading')
('Putting back', 'numpy.polynomial.laguerre')
('Putting back', 'numpy.core._methods')
('Putting back', 'numpy.fft.fftpack_lite')
('Putting back', 'numpy.core.function_base')
('Putting back', 'numpy.add_newdocs')
('Putting back', 'numpy.core.umath')
('Putting back', 'numpy.lib.index_tricks')
('Putting back', 'numpy.polynomial.hermite')
('Putting back', 'numpy')
('Putting back', 'numpy.polynomial.polyutils')
('Putting back', 'numpy.polynomial.chebyshev')
('Putting back', 'numpy.fft.helper')
('Putting back', 'numpy.polynomial.hermite_e')
('Putting back', 'numpy.core.fromnumeric')
('Putting back', 'numpy.lib.utils')
('Putting back', 'numpy.core.defchararray')
('Putting back', 'numpy.lib.arraysetops')
('Putting back', 'numpy.lib.function_base')
('Putting back', 'numpy.polynomial.polynomial')
('Putting back', 'numpy.ma')
('Putting back', 'numpy.compat.py3k')
('Putting back', 'numpy.lib.ufunclike')
('Putting back', 'numpy.lib.info')
('Putting back', 'numpy.compat._inspect')
('Putting back', 'numpy.ma.core')
('Putting back', 'numpy.testing.utils')
('Putting back', 'numpy.version')
('Putting back', 'numpy.lib.stride_tricks')
('Putting back', 'numpy.lib.format')
('Putting back', 'numpy.lib.arrayterator')
('Putting back', 'numpy.testing.nosetester')
('Putting back', 'numpy.core.machar')
('Putting back', 'numpy.core.getlimits')
('Putting back', 'numpy.lib.type_check')
('Putting back', 'numpy.ctypeslib')
('Putting back', 'numpy.matrixlib.defmatrix')
('Putting back', 'numpy.polynomial._polybase')
('Putting back', 'numpy.lib.scimath')
('Putting back', 'numpy.core.memmap')
('Putting back', 'numpy.linalg._umath_linalg')
('Putting back', 'numpy.fft')
('Putting back', 'numpy.lib')
('Putting back', 'numpy.lib.nanfunctions')
('Putting back', 'numpy.lib._datasource')
('Putting back', 'numpy.ma.extras')
('Putting back', 'numpy.core._internal')
('Putting back', 'numpy.fft.fftpack')
('Putting back', 'numpy.linalg.lapack_lite')
('Putting back', 'numpy.core.multiarray')
('Putting back', 'numpy.lib._version')
('Putting back', 'numpy.lib.arraypad')
Traceback (most recent call last):
  File "test.py", line 332, in <module>
    print('>>', sys.modules['numpy.core'])
KeyError: 'numpy.core'

niklas@niklas-PC /cygdrive/c/Users/niklas/Desktop
$ /cygdrive/c/maxon/Cinema\ 4D\ R17\ Dev/resource/modules/python/Python.win64.framework/python test.py
[1 2 3]
('Putting back', 'numpy.random.warnings')
('Putting back', 'numpy.linalg.linalg')
('Putting back', 'numpy.lib._iotools')
('Putting back', 'numpy.random.operator')
('Putting back', 'numpy.core.info')
('Putting back', 'numpy.core.shape_base')
('Putting back', 'numpy.core')
('Putting back', 'numpy.linalg')
('Putting back', 'numpy.random')
('Putting back', 'numpy.lib.shape_base')
('Putting back', 'numpy.lib.polynomial')
('Putting back', 'numpy.compat')
('Putting back', 'numpy._import_tools')
('Putting back', 'numpy.lib.twodim_base')
('Putting back', 'numpy.core.numeric')
('Putting back', 'numpy.polynomial')
('Putting back', 'numpy.fft.info')
('Putting back', 'numpy.core.records')
('Putting back', 'numpy.core.numerictypes')
('Putting back', 'numpy.polynomial.legendre')
('Putting back', 'numpy.random.mtrand')
('Putting back', 'numpy.__config__')
('Putting back', 'numpy.matrixlib')
('Putting back', 'numpy.random.numpy')
('Putting back', 'numpy.lib.financial')
('Putting back', 'numpy.random.info')
('Putting back', 'numpy.testing.decorators')
('Putting back', 'numpy.linalg.info')
('Putting back', 'numpy.lib.npyio')
('Putting back', 'numpy.testing')
('Putting back', 'numpy.lib.numpy')
('Putting back', 'numpy.core.arrayprint')
('Putting back', 'numpy.random.threading')
('Putting back', 'numpy.polynomial.laguerre')
('Putting back', 'numpy.core._methods')
('Putting back', 'numpy.fft.fftpack_lite')
('Putting back', 'numpy.core.function_base')
('Putting back', 'numpy.add_newdocs')
('Putting back', 'numpy.core.umath')
('Putting back', 'numpy.lib.index_tricks')
('Putting back', 'numpy.polynomial.hermite')
('Putting back', 'numpy')
('Putting back', 'numpy.polynomial.polyutils')
('Putting back', 'numpy.polynomial.chebyshev')
('Putting back', 'numpy.fft.helper')
('Putting back', 'numpy.polynomial.hermite_e')
('Putting back', 'numpy.core.fromnumeric')
('Putting back', 'numpy.lib.utils')
('Putting back', 'numpy.core.defchararray')
('Putting back', 'numpy.lib.arraysetops')
('Putting back', 'numpy.lib.function_base')
('Putting back', 'numpy.polynomial.polynomial')
('Putting back', 'numpy.ma')
('Putting back', 'numpy.compat.py3k')
('Putting back', 'numpy.lib.ufunclike')
('Putting back', 'numpy.lib.info')
('Putting back', 'numpy.compat._inspect')
('Putting back', 'numpy.ma.core')
('Putting back', 'numpy.testing.utils')
('Putting back', 'numpy.version')
('Putting back', 'numpy.lib.stride_tricks')
('Putting back', 'numpy.lib.format')
('Putting back', 'numpy.lib.arrayterator')
('Putting back', 'numpy.testing.nosetester')
('Putting back', 'numpy.core.machar')
('Putting back', 'numpy.core.getlimits')
('Putting back', 'numpy.lib.type_check')
('Putting back', 'numpy.ctypeslib')
('Putting back', 'numpy.matrixlib.defmatrix')
('Putting back', 'numpy.polynomial._polybase')
('Putting back', 'numpy.lib.scimath')
('Putting back', 'numpy.core.memmap')
('Putting back', 'numpy.linalg._umath_linalg')
('Putting back', 'numpy.fft')
('Putting back', 'numpy.lib')
('Putting back', 'numpy.lib.nanfunctions')
('Putting back', 'numpy.lib._datasource')
('Putting back', 'numpy.ma.extras')
('Putting back', 'numpy.core._internal')
('Putting back', 'numpy.fft.fftpack')
('Putting back', 'numpy.linalg.lapack_lite')
('Putting back', 'numpy.core.multiarray')
('Putting back', 'numpy.lib._version')
('Putting back', 'numpy.lib.arraypad')
('Disabling', 'numpy.fft.fftpack_lite')
('Disabling', 'numpy.core.info')
('Disabling', 'numpy.polynomial.legendre')
('Disabling', 'numpy.random.mtrand')
('Disabling', 'numpy.random.threading')
('Disabling', 'numpy.__config__')
('Disabling', 'numpy.matrixlib.defmatrix')
('Disabling', 'numpy.random.info')
('Disabling', 'numpy.linalg')
('Disabling', 'numpy.core.machar')
('Disabling', 'numpy.core.umath')
('Disabling', 'numpy.lib.numpy')
('Disabling', 'numpy.polynomial._polybase')
('Disabling', 'numpy.lib.arraysetops')
('Disabling', 'numpy.version')
('Disabling', 'numpy.polynomial.polyutils')
('Disabling', 'numpy.lib.type_check')
('Disabling', 'numpy.core._internal')
('Disabling', 'numpy.random.operator')
('Disabling', 'numpy.lib._datasource')
('Disabling', 'numpy.core.multiarray')
('Disabling', 'numpy.lib')
('Disabling', 'numpy.linalg._umath_linalg')
('Disabling', 'numpy.polynomial.polynomial')
('Disabling', 'numpy.polynomial')
('Disabling', 'numpy.add_newdocs')
('Disabling', 'numpy.core.getlimits')
('Disabling', 'numpy.core.arrayprint')
('Disabling', 'numpy.matrixlib')
('Disabling', 'numpy.ma.extras')
('Disabling', 'numpy.testing.decorators')
('Disabling', 'numpy.lib.npyio')
('Disabling', 'numpy.core.numerictypes')
('Disabling', 'numpy.fft.helper')
('Disabling', 'numpy.lib.info')
('Disabling', 'numpy.polynomial.laguerre')
('Disabling', 'numpy.core.shape_base')
('Disabling', 'numpy.lib.shape_base')
('Disabling', 'numpy.compat._inspect')
('Disabling', 'numpy.ma')
('Disabling', 'numpy.core._methods')
('Disabling', 'numpy.random')
('Disabling', 'numpy.lib.twodim_base')
('Disabling', 'numpy.ma.core')
('Disabling', 'numpy.lib.financial')
('Disabling', 'numpy.testing')
('Disabling', 'numpy.core.function_base')
('Disabling', 'numpy.compat.py3k')
('Disabling', 'numpy.lib.stride_tricks')
('Disabling', 'numpy')
('Disabling', 'numpy.polynomial.chebyshev')
('Disabling', 'numpy.polynomial.hermite_e')
('Disabling', 'numpy.testing.nosetester')
('Disabling', 'numpy.testing.utils')
('Disabling', 'numpy.lib.ufunclike')
('Disabling', 'numpy.core.fromnumeric')
('Disabling', 'numpy.ctypeslib')
('Disabling', 'numpy.lib.scimath')
('Disabling', 'numpy.fft')
('Disabling', 'numpy.lib.nanfunctions')
('Disabling', 'numpy.random.numpy')
('Disabling', 'numpy.core.memmap')
('Disabling', 'numpy.lib.arraypad')
('Disabling', 'numpy.lib.function_base')
('Disabling', 'numpy.lib._version')
('Disabling', 'numpy.random.warnings')
('Disabling', 'numpy.fft.fftpack')
('Disabling', 'numpy.lib.polynomial')
('Disabling', 'numpy.compat')
('Disabling', 'numpy._import_tools')
('Disabling', 'numpy.polynomial.hermite')
('Disabling', 'numpy.fft.info')
('Disabling', 'numpy.core.records')
('Disabling', 'numpy.core.numeric')
('Disabling', 'numpy.linalg.info')
('Disabling', 'numpy.core.defchararray')
('Disabling', 'numpy.core')
('Disabling', 'numpy.lib._iotools')
('Disabling', 'numpy.lib.index_tricks')
('Disabling', 'numpy.lib.utils')
('Disabling', 'numpy.linalg.lapack_lite')
('Disabling', 'numpy.lib.format')
('Disabling', 'numpy.lib.arrayterator')
('Disabling', 'numpy.linalg.linalg')
Traceback (most recent call last):
  File "test.py", line 333, in <module>
    print('>>', sys.modules['numpy.core'])
KeyError: 'numpy.core'
```

Problem is this part of the code:

``` python

        # If this function is called not the first time, we need to
        # restore the modules that have been imported with it and
        # temporarily disable the ones that would be shadowed.
        for key, mod in self.modules.items():
            try: self.state['disables'][key] = sys.modules.pop(key)
            except KeyError: pass
            sys.modules[key] = mod
            print('Putting back', key)

        # Evaluate .pth files.
        if self.do_pth:
            for path_name in self.path:
                for fn in glob.glob(os.path.join(path_name, '*.pth')):
                    self._eval_pth(fn, path_name)

        # Disable all modules that can be imported from the local site
        # but that have already been imported from another to avoid
        # possible collisions (#12).
        for path in sys.path:
            for module in self._discover(path):
                sub = module + '.'
                for key, mod in sys.modules.items():
                    if key == module or key.startswith(sub):
                        print('Disabling', key)
                        self.state['disables'][key] = sys.modules.pop(key)
```

**Comment by NiklasRosenstein** [comment]
We just have to switch the _re-add_ with the _remove local replacements_ part.
