### ISSUE TITLE
__enter__: Dictionary changed size during iteration

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/localimport#17]
This error happened when using localimport in an application created with PyInstaller.

```
$ dist/gitlab-manage/gitlab-manage.exe
Traceback (most recent call last):
  File "pyinstaller-bootstrap.py", line 8, in <module>
    nodepy.main(['--current-dir', os.path.dirname(__file__), './gui.py'])
  File "nodepy.py", line 1258, in main
  File "nodepy.py", line 1282, in _main
  File "nodepy.py", line 899, in __enter__
  File "site-packages\localimport.py", line 145, in __enter__
RuntimeError: dictionary changed size during iteration
Failed to execute script pyinstaller-bootstrap
```

**Comment by NiklasRosenstein** [comment]
It's an error with Python 3, as `dict.items()` yields a `dict_view` object and the dictionary must not changed during iteration over this object.
