### ISSUE TITLE
Installation inside a Docker container fails

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/localimport#19]
```Dockerfile
FROM ubuntu:16.04
RUN apt-get install -y python3 python3-pip > /dev/null
RUN pip3 install localimport
```

Results in

```
  Downloading localimport-1.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jfrxurzp/localimport/setup.py", line 20, in <module>
        long_description = restify(),
      File "/tmp/pip-build-jfrxurzp/localimport/setup.py", line 14, in restify
        return fp.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 28: ordinal not in range(128)
```

**Comment by NiklasRosenstein** [comment]
Using 

```Dockerfile
ENV LANG C.UTF-8
```

in the Dockerfile makes it work, but we should probably just open the README file with a proper encoding.
